// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fd00f988-f7b8-4790-9c97-b94778bf2d11";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCvoltHighChange();
void onCvoltLowChange();
void onCpowerswitchChange();

CloudElectricCurrent ccurrent;
CloudElectricPotential cvoltage;
float cenergy;
float cpF;
CloudFrequency cfrequency;
int cvoltHigh;
int cvoltLow;
CloudPower cpower;
bool cpowerswitch;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ccurrent, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cvoltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cenergy, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cpF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cfrequency, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cvoltHigh, READWRITE, ON_CHANGE, onCvoltHighChange);
  ArduinoCloud.addProperty(cvoltLow, READWRITE, ON_CHANGE, onCvoltLowChange);
  ArduinoCloud.addProperty(cpower, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(cpowerswitch, READWRITE, ON_CHANGE, onCpowerswitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
