// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0ea7b40d-b382-465a-8337-9c432db1f94a";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


int carpetSystemC;
int computerVisionC;
int system_countC;
CloudLocation locationC;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(carpetSystemC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(computerVisionC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(system_countC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(locationC, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
